name: Update LeetCode Stats

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Fetch LeetCode stats
      run: |
        python fetch_leetcode_stats.py

    - name: Commit changes
      run: |
        git config --local user.email "shubhampatel2024@gmail.com"
        git config --local user.name "Shubham Patel"
        git add .
        git commit -m "Update LeetCode stats"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git push https://$GITHUB_TOKEN@github.com/imshubhampatel/imshubhampatel.git HEAD:main
