name: Update LeetCode Stats

on:
  schedule:
    # Run this action daily (set according to your preference)
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Fetch LeetCode stats
      run: |
        python fetch_leetcode_stats.py

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update LeetCode stats"
        git push
